### ISSUE TITLE
ssh not installed by default

### ISSUE THREAD

**Issue by mash1t** [bitnami/bitnami-docker-jenkins#37]
The following error occurs when entering a git repository url on a project after setting up jenkins:

```
Failed to connect to repository : Command "git ls-remote -h git@github.com:bitnami/bitnami-docker-jenkins.git HEAD" returned status code 128:
stdout: 
stderr: error: cannot run ssh: No such file or directory
fatal: unable to fork
```

After installing openssl-server in the container via

```
apt-get install openssh-server
```
everything just works fine.

It would be great if you could include the possibility to use ssh by default.

**Comment by dgonzalezruiz** [comment]
Hi @mash1t ,

latest revision released fixed this issue! Please, check it out in case you still feel there's anything missing.

Thanks a lot for your feedback! 😄

**Comment by dgonzalezruiz** [comment]
Hi @mash1t ,

Thanks a lot for your feedback! I released a new revision of the image fixing this issue. Let me know if you encounter any issues.

**Comment by miked0004** [comment]
I was having this problem, `apt-get install openssh-client` is probably more what you'd want.

**Comment by rafariossaa** [comment]
Hi @miked0004,
  At the end that was the package we included.

Thanks,
