### ISSUE TITLE
Please include maven

### ISSUE THREAD

**Issue by ptahchiev** [bitnami/bitnami-docker-jenkins#43]
I can see gradle is included in `/opt/bitnami/` but there is no maven. Most people use maven to build their software.

**Comment by andresbono** [comment]
Hi @ptahchiev,

We try to make our images as lightweight as possible so we only include the essential packages for each application.

I would recommend you to create your own Dockerfile inheriting from `bitnami/jenkins`, adding any additional components you need for your custom Jenkins setup.

Anyway, if more people come with the same request, we will consider to include it.

Thanks for choosing Bitnami images!
