### ISSUE TITLE
Missing jre folder.

### ISSUE THREAD

**Issue by ptahchiev** [bitnami/bitnami-docker-jenkins#44]
The `/opt/bitnami/java` folder is missing `jre` subfolder. This seems to be invalid installation. By default maven is looking for the tools.jar in ${java.home}/../lib/tools.jar.

**Comment by andresbono** [comment]
Hi @ptahchiev,

Please, fill the template automatically provided when you open a new issue in this repo.
It will be much easier to understand your issue and actually help you with it.

------------------

Java Home is `/opt/bitnami/java`. JRE is placed there. As official documents say:
>The JAVA_HOME path should point to the location that you recorded when you installed the JRE.

- Can you provide more information about your environment?
- Why do you expect a `jre` folder inside JAVA HOME?
- Could you give us more information about how did you install maven in the Jenkins container?

**Comment by ptahchiev** [comment]
Hello,

here's what I have in my JAVA_HOME when I install Java from the Oracle website:
````
$ ls -al $JAVA_HOME
total 25932
drwxr-xr-x 8 root root     4096 Mar  8 09:30 .
drwxr-xr-x 6 root root     4096 Mar  8 09:30 ..
drwxr-xr-x 2 root root     4096 Mar  8 09:30 bin
-r--r--r-- 1 root root     3244 Mar  8 09:30 COPYRIGHT
drwxr-xr-x 4 root root     4096 Mar  8 09:30 db
drwxr-xr-x 3 root root     4096 Mar  8 09:30 include
-rwxr-xr-x 1 root root  5094116 Mar  8 09:30 javafx-src.zip
drwxr-xr-x 5 root root     4096 Mar  8 09:30 jre      <-------- NOTICE THIS FOLDER?
drwxr-xr-x 5 root root     4096 Mar  8 09:30 lib
-r--r--r-- 1 root root       40 Mar  8 09:30 LICENSE
drwxr-xr-x 4 root root     4096 Mar  8 09:30 man
-r--r--r-- 1 root root      159 Mar  8 09:30 README.html
-rw-r--r-- 1 root root      526 Mar  8 09:30 release
-rw-r--r-- 1 root root 21116095 Mar  8 09:30 src.zip
-rwxr-xr-x 1 root root   110114 Mar  8 09:30 THIRDPARTYLICENSEREADME-JAVAFX.txt
-r--r--r-- 1 root root   177094 Mar  8 09:30 THIRDPARTYLICENSEREADME.txt
````

Here's what you have in your `/opt/bitnami/java` folder:

````
$ ls -al /opt/bitnami/java
total 332
drwxr-xr-x  7 root    root   4096 Apr 18 07:31 .
drwxr-xr-x 19 root    root   4096 Apr 27 07:26 ..
drwxr-xr-x  2 root    root   4096 Apr 18 07:27 bin
drwxr-xr-x  2 bitnami root   4096 Apr 27 07:48 bitnami
-r--r--r--  1 root    root   3244 Dec 13 00:46 COPYRIGHT
drwxr-xr-x 15 root    root   4096 Apr 18 07:27 lib
-r--r--r--  1 root    root     40 Dec 13 00:46 LICENSE
drwxr-xr-x  4 root    root   4096 Apr 18 07:27 man
drwxr-xr-x  3 root    root   4096 Apr 18 07:27 plugin
-r--r--r--  1 root    root     46 Dec 13 00:46 README
-rw-r--r--  1 root    root    526 Dec 13 00:46 release
-rwxr-xr-x  1 root    root 110114 Dec 12 20:10 THIRDPARTYLICENSEREADME-JAVAFX.txt
-r--r--r--  1 root    root 177094 Dec 13 00:46 THIRDPARTYLICENSEREADME.txt
-r--r--r--  1 root    root    955 Dec 13 00:46 Welcome.html
````
Where the hell is `jre` folder?

Now it becomes interesting when you try to build a project which has this dependency in their build script:
````
        <dependency>
            <groupId>com.google.testing.compile</groupId>
            <artifactId>compile-testing</artifactId>
        </dependency>
````
which brings as a transitive dependency this:
````
    <dependency>
      <groupId>com.sun</groupId>
      <artifactId>tools</artifactId>
      <version>${java.version}</version>
      <scope>system</scope>
      <systemPath>${java.home}/../lib/tools.jar</systemPath>
    </dependency>
````

The project builds fine on my machine, but breaks on yours, because Maven resolves ${java.home} as `$JAVA_HOME/jre` on standard Java installation. However, on the bitnami installation it resolves it as  $JAVA_HOME so it tries to find `tools.jar` inside `$JAVA_HOME/../lib/tools.jar` and of course it is not there!!!
Why did you remove the jre folder? Why is JRE_HOME environment variable pointing to `/opt/bitnami/java`???

I installed maven with wget and unzip - pretty standard.

**Comment by javsalgar** [comment]
Hi, 

From the other issues you opened, it looks like you are using our Cloud Images, right? Could you please post the issues in community.bitnami.com?
