### ISSUE TITLE
Add firefox to the image.

### ISSUE THREAD

**Issue by ptahchiev** [bitnami/bitnami-docker-jenkins#45]
A lot of people use jenkins to run selenium integration tests and having firefox installed would be very useful.

**Comment by carrodher** [comment]
Hi @ptahchiev,

We try to make our images as lightweight as possible so we only include the essential packages for each application. If we include by default the packages that users demand, our images would be really heavy. Only in the case of having a great demand we consider including a package by default.

I would recommend you to create your own Dockerfile inheriting from `bitnami/jenkins`, adding any additional components you need for your custom Jenkins setup.

Also, you can find information about ["How to configure slaves as Docker containers?"](https://docs.bitnami.com/google/apps/jenkins/#configure_slaves) in our docs, you can follow this guide but installing Firefox and Selenium if you want to use a master-slave configuration.

Thanks for choosing Bitnami images!
