### ISSUE TITLE
Mod_pagespeed in Apache causes the log output to stop

### ISSUE THREAD

**Issue by ptahchiev** [bitnami/bitnami-docker-jenkins#46]
Please look at this issue in official Jenkins JIRA:

https://issues.jenkins-ci.org/browse/JENKINS-25026

The mod_pagespeed you ship configured in Apache HTTD causes the output log to be stopeed while tailing the log so we need to manually stop that shit. Please have it removed from the apache!!!!

**Comment by javsalgar** [comment]
Hi, 

We do not have `pagespeed` in our Bitnami Jenkins container. Could it be that you are referring to our Bitnami Jenkins Cloud Image? If that is the case, please go to our Community page community.bitnami.com, where we can help you with the issue.
