### ISSUE TITLE
What's the default user and password?

### ISSUE THREAD

**Issue by mengwang0211** [bitnami/bitnami-docker-jenkins#50]
What's the default user and password?
Please tell me 

[docker-compose up -d]

**Comment by juan131** [comment]
Hi @mengwang0211 

As you can check in the **README.md** file, the default credentials are:

- Jenkins admin username. Default: **user**
- Jenkins admin password. Default: **bitnami**

Link: https://github.com/bitnami/bitnami-docker-jenkins#environment-variables

**Comment by mengwang0211** [comment]
> Hi @mengwang0211
> 
> As you can check in the **README.md** file, the default credentials are:
> 
> * Jenkins admin username. Default: **user**
> * Jenkins admin password. Default: **bitnami**
> 
> Link: https://github.com/bitnami/bitnami-docker-jenkins#environment-variables

thank u so much,bro

**Comment by juan131** [comment]
You're welcome @mengwang0211 

I proceed to close this issue as 'solved'. Please reopen it if you need further assistance.
