### ISSUE TITLE
Plugin Publish Over SSH not work

### ISSUE THREAD

**Issue by giangsoda** [bitnami/bitnami-docker-jenkins#54]
Please help me with plugin ssh:

- I use image bitnami/jenkins:2, and docker-compose
- Install plugin Publish Over SSH Plugin [https://wiki.jenkins.io/display/JENKINS/Publish+Over+SSH+Plugin](https://wiki.jenkins.io/display/JENKINS/Publish+Over+SSH+Plugin)
- Config not work with remote ssh to another server, message error `jenkins.plugins.publish_over.BapPublisherException: Failed to connect and initialize SSH connection. Message: [Failed to connect SFTP channel. Message [channel is not opened.]]`

**Comment by tompizmor** [comment]
Hi @giangsoda,

Can you check if this post from StackOverflow helps? A user reported the same issue.

https://stackoverflow.com/questions/22345483/jenkins-publish-over-ssh-authentification-failed-with-private-key

**Comment by andymel123** [comment]
I had the same problem...for people finding this:

My Jenkins user was created with ansible and due to a copy-paste error it had **no login shell**!

**Comment by andresbono** [comment]
Hi @andymel123, did you solve the issue in the end?

**Comment by jimizai** [comment]
Hi @andymel123, did you solve the issue in the end?

**Comment by andymel123** [comment]
Hi @andresbono & @jimizai,
yes, I simply allow shell login for the Jenkins user :)

**Comment by andresbono** [comment]
Thanks for confirming!
