### ISSUE TITLE
Invalid credentials after recreating pod

### ISSUE THREAD

**Issue by mrmunch** [bitnami/bitnami-docker-jenkins#55]
**Invalid credentials after recreating pod**

I run this jenkins image as a single pod in my k8s cluster (AKS). I use a pvc for jenkins_home to make sure my config isn't lost after recreating the pod.
After first startup, I installed the Crowd2 plugin in configured Crowd authentication. It was successful.
After that, I recreated my pod. Now I am not able anymore to login. Pod log:

`WARNING d.t.j.c.CrowdConfigurationService#isGroupMember: Application name and/or password are not valid.`

I compared my config.xml from the first pod and the config.xml from the 2nd pod. I see the encrypted password value for my Crowd application has changed.
How can that be? As I said, I use a pvc, so all the config files should stay the same. But it looks like (all?) encrypted passwords have changed after the pod was recreated.

**Steps to reproduce the issue:**

1. Run jenkins image in an K8s with a pvc on jenkins_home (single pod)
2. Install Crowd2 plugin
3. Configure Crowd2 plugin with your Crowd instance
4. Try to login with your Crowd credentials -> success
5. Recreate the pod (for example, "kubectl delete pod <pod-id>" so K8s will automatically recreate the pod)
6. After recreation/restart on Jenkins, try to login with your Crowd credentials -> fails

**Comment by javsalgar** [comment]
Hi,

Let me see if I understand correctly. The regular user and password for Jenkins work, it is this Crowd authentication (which I do not know much about) the one that gets regenerated for some reason, right?

**Comment by mrmunch** [comment]
Hi,
problem solved.
I had to set disableInitialization=true in my helm chart.

**Comment by javsalgar** [comment]
Hi,

Good to know! Do not hesitate to open a new ticket if you find other issues
