### ISSUE TITLE
Node Project having issue - npm ERR! code EACCES path /.npm

### ISSUE THREAD

**Issue by santoshshinde2012** [bitnami/bitnami-docker-jenkins#58]
**Description**

Node project having an issue to run the build stage as  `npm ERR! code EACCES path /.npm`. 

I have followed the following steps and set up the project. 

`$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-jenkins/master/docker-compose.yml > docker-compose.yml`
`$ docker-compose up -d`

**Steps to reproduce the issue:**

Running following file 

```
pipeline {
    agent any

    tools {
        nodejs "node"
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm i'
                sh 'npm run build'
            }
        }
...
``` 
**Describe the results you received:**

```
+ npm i
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:0 "/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:0 "/.npm"
npm ERR! Response timeout while trying to fetch https://registry.npmjs.org/npm (over 30000ms)
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.778GiB
 Name: docker-desktop
 ID: WWWF:SYQ3:EXLJ:VXK5:NG64:3KAX:QB6U:MYGJ:QJFV:T7T7:5BDZ:WCYR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 58
  System Time: 2020-04-12T08:55:20.7345879Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

Please let me know if I am missing anything or where I need to give any permission to fix the issue.

**Comment by dani8art** [comment]
Hi @santoshshinde2012 sorry but I was not able to reproduce your issue, could you send me the exact steps you followed, please?

**Comment by santoshshinde2012** [comment]
I am running this [image](https://github.com/bitnami/bitnami-docker-jenkins/blob/master/docker-compose.yml) on my local(Mac) machine.

But Jenkins build failed at the stage of `npm install` due to permission issue for the current user.

**Comment by dani8art** [comment]
Sorry @santoshshinde2012, I did not explain well before. I follow the steps you posted in your first comment but I was not able to reproduce the issue because I'm not able to run this script in jenkins
```
pipeline {
    agent any

    tools {
        nodejs "node"
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm i'
                sh 'npm run build'
            }
        }
```
I got this error something like `nodejs is not a valid tool`, So I would need to know what you did and then I could suggest the best approach.

**Comment by santoshshinde2012** [comment]
> Sorry @santoshshinde2012, I did not explain well before. I follow the steps you posted in your first comment but I was not able to reproduce the issue because I'm not able to run this script in jenkins
> 
> ```
> pipeline {
>     agent any
> 
>     tools {
>         nodejs "node"
>     }
>     stages {
>         stage('Build') {
>             steps {
>                 sh 'npm i'
>                 sh 'npm run build'
>             }
>         }
> ```
> 
> I got this error something like `nodejs is not a valid tool`, So I would need to know what you did and then I could suggest the best approach.

you need to add a nodejs

**Comment by dani8art** [comment]
Hi @santoshshinde2012, Could you provide the exact steps to reproduce the issue, please?, I would need to reproduce it in my environment so that I can help you. Thank you in advance!

**Comment by dani8art** [comment]
Hi @santoshshinde2012 any updates?
