### ISSUE TITLE
How to authenticate AWS credentials from a file in bitnami jenkins

### ISSUE THREAD

**Issue by gopimanne24** [bitnami/bitnami-docker-jenkins#61]
Hi..I want to authenticate AWS ECS service from the jenkins UI by passing aws user keys from a file from the jenkins server. For that i am using aws credentials helper but still i can not able to login. Could you please suggest how can i authenticate aws user from a file so that i no need to pass any aws user information in the jenkins UI?

**Comment by javsalgar** [comment]
Hi,

Several of our charts allow mounting extra volumes so you can add your custom configmaps or secrets. If we add this option to the chart, then you could mount the files you require. However, how to configure Jenkins so it uses this file is something that I have not done before. Did you check the Jenkins documentation for more information on that?

**Comment by gopimanne24** [comment]
Hi,
Jenkins documentation suggesting to store secrets in credentails in jenkins UI and use as secret text as binding but my concern here is i am using a service AWS ECR where i need to push my images to ECR Registry from Jenkins job which need to be authenticated every time before pushing. So instead of passing the credentials as binding from UI, I want to store my aws keys in a file in the jenkins server at some path and i want to use that path in Jenkins UI to authenticate during CI/CD process so that i no need to display my keys in the Jenkins UI. Is this possible to do ? Any suggestions?

**Comment by javsalgar** [comment]
Hi,

The solution is to add the extraVolume and extraVolumeMounts values to our chart so you can mount whatever secret you want in any location. Stay tuned because we will implement these changes very soon in the chart. If you want to speed up the process, feel free to submit a PR (you can see examples in Joomla, Kong and other charts).
