### ISSUE TITLE
Can't login if i use JENKINS_USERNAME=admin every other name works fine

### ISSUE THREAD

**Issue by antonio-piha** [bitnami/bitnami-docker-jenkins#62]
**Description**

Can't login if i use JENKINS_USERNAME=admin every other name works fine

**Steps to reproduce the issue:**

1. set JENKINS_USERNAME=admin

**Describe the results you received:**

 Invalid username or password

**Describe the results you expected:**

Login successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Any other username works fine

**Version**

- Output of `docker version`:

```
Docker version 19.03.12, build 48a66213fe
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running in K3s on premise

**Comment by miguelaeh** [comment]
Hi @antonio-piha ,
Thank you very much for reporting this issue. I am able to replicate it.
I have been looking into the official docs if the user `admin` is not allowed but I didn't find anything. Do you have any ideas about that? Have ever used `admin` as user before?

**Comment by antonio-piha** [comment]
Hello @miguelaeh,

Found something here:
https://www.jenkins.io/doc/book/installing/#unlocking-jenkins

under third point "3. On the Unlock Jenkins page"

> This password also serves as the default admininstrator account’s password (with username "admin")

And mentioned file is in the container too:
`jenkins@jenkins-bitnami-6487466858-6tdhz:/$ cat bitnami/jenkins/jenkins_home/secrets/initialAdminPassword
ee9b4309c5f24daf97bba719c882df2e
`

So there is a default user "admin", I'd suggest putting this in the readme somewhere, to not try setting  JENKINS_USERNAME env to admin.

**Comment by miguelaeh** [comment]
Hi @antonio-piha ,
Thank you very much for your suggestion. Would you like to create a PR adding that?
