### ISSUE TITLE
JENKINS_USERNAME and JENKINS_PASSWORD have no effect on a fresh container using persisted data

### ISSUE THREAD

**Issue by GraysonCAdams** [bitnami/bitnami-docker-jenkins#64]
**Description**

When you deploy with `helm install my-release bitnami/jenkins`  it generates a username and password. Subsequent `helm upgade`'s change that password value every time in the secrets store. The secret gets passed in to the Docker container as `JENKINS_PASSWORD`

It seems as though no matter what `JENKINS_PASSWORD` is changed to, the password is the same as the very first deployment.

Any ideas as to why this might be? Why have helm inform of a new updated password + override the old password secret on upgrades if the password does not actually change? It overrides the correct secret with now an inaccurate secret.

**Steps to reproduce the issue:**

1. Deploy Jenkins with Helm `helm install my-release bitnami/jenkins`
2. Run `echo Password: $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-password}" | base64 --decode)`
3. Log in with the password to Jenkins
4. Upgrade Jenkins:  `helm upgrade my-release bitnami/jenkins`
5. Run `echo Password: $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-password}" | base64 --decode)`
6. Note that the password has changed. Try logging in with the password, it will not work
7. Check Kubernetes jenkins.password secret and find it has also been overwritten with  the new, incorrect password
8. Log in with your original password from the first deployment, it will work
9. Try redeploying containers to see if they pull new secret, but they do not

**Describe the results you received:**

Password secret is overwritten by Helm upgrade, new password is passed in as `JENKINS_PASSWORD` to container, but Jenkins does not use the new password.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 35
  Running: 26
  Paused: 0
  Stopped: 9
 Images: 15
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-122-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.853GiB
 Name: ranchernode1
 ID: IX2Z:VJR2:6X7B:A3O4:WAAX:VH7H:FEKP:ZRRU:RVK3:26HX:52PV:2ONA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by carrodher** [comment]
Thanks for creating the issue, when upgrading you need to pass as parameter the existing password, as those passwords are stored in the PV/PVC and those objects are not recreated with `helm upgrade` there is an inconsistency between the first stored random password and the one created during the upgrade.

In this [troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases) you can find more info about how the upgrades are handled by Bitnami Helm Charts and how to solve the issue once the upgrade was already done.
