### ISSUE TITLE
'Error: EACCES: permission denied when building Angular app'

### ISSUE THREAD

**Issue by tdespenza** [bitnami/bitnami-docker-jenkins#70]
**Description**

**Steps to reproduce the issue:**

1. Create an **NRWL** app
2. Add the NodeJS plugin with the latest v14 version
3. Install yarn globally
4. Setup a basic freestyle pipeline
5. Run `yarn run nx build app --prod`

**Describe the results you received:**

`Error: EACCES: permission denied, mkdir `during the build process

**Describe the results you expected:**

A successful build

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 13
  Running: 12
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: tdespenza
 ID: YVPQ:U62Z:WQXU:FNCP:HLHI:GDT5:Z3BR:7POI:NN7S:YF4E:JYKZ:3IRZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

I'm running in Portainer on DigitalOcean.

<img width="944" alt="Screen Shot 2021-08-19 at 7 25 54 AM" src="https://user-images.githubusercontent.com/3230907/130069232-c6f822f8-adc6-4d7a-a49e-9d9f23e7858d.png">

<img width="1438" alt="Screen Shot 2021-08-19 at 7 31 14 AM" src="https://user-images.githubusercontent.com/3230907/130069249-fd843a7d-0a3d-42e7-9346-57e02651d36b.png">

<img width="1423" alt="Screen Shot 2021-08-19 at 7 31 32 AM" src="https://user-images.githubusercontent.com/3230907/130069364-0b05ca84-5aff-4198-9d55-2d0621beb3b9.png">

<img width="1571" alt="Screen Shot 2021-08-19 at 7 32 01 AM" src="https://user-images.githubusercontent.com/3230907/130069377-d5c58f93-5fe7-468e-9add-bc3e9f9659ed.png">

<img width="1448" alt="Screen Shot 2021-08-19 at 7 32 25 AM" src="https://user-images.githubusercontent.com/3230907/130069401-fe978088-6494-4a06-8e42-d983ccb6e9f6.png">

**Comment by javsalgar** [comment]
Hi,

It seems to me that the issue is related to a missing HOME directory, which is causing issues when dealing with node.js installations. Could you try installing without the `-g` parameter? Would it work?

**Comment by tdespenza** [comment]
That's something that's controlled by the plugin to install it globally on the first run. But after I fixed the directory issue. I run into the `sudo` issue again. It seems that this bitnami image doesn't contain the `sudo` command.

<img width="898" alt="Screen Shot 2021-08-20 at 7 41 57 AM" src="https://user-images.githubusercontent.com/3230907/130235788-9185131c-7751-4158-b4ff-fcd44c3a2efa.png">

**Comment by javsalgar** [comment]
Yes, that's expected to not include sudo (in terms of security it would privilege escalation). How did you fix the directory issue? Which are the permissions of the created folder?

**Comment by tdespenza** [comment]
I never fixed the directory issue. I just switched to a different CI image.

**Comment by javsalgar** [comment]
I'll create a task for investigating what to do in scenarios where root privileges are required. For the time being, you could try launching the image with `user: root` in the docker-compose file.
