### ISSUE TITLE
how to add Sonar plugins for init jenkins?

### ISSUE THREAD

**Issue by smarttang** [bitnami/bitnami-docker-jenkins#76]
**Description**

I am in the image based on bitnami/jenkins:2.303.3 and want to add sonar support, but I can’t get started. Do you have a guide to add support for plug-ins?
In addition, when I want to add a custom account and password to the groovy script, I find that it will cause the ulock of the Jenkins service to be manually unlocked. Is there any way to solve this problem?

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi, 
  Could you take a look to [this](https://github.com/bitnami/bitnami-docker-jenkins#user-content-preinstalling-plugins) ?.
  Regarding the jenkins unlock, could you provide more information. I am not very sure what you mean.

**Comment by smarttang** [comment]
> Hi, Could you take a look to [this](https://github.com/bitnami/bitnami-docker-jenkins#user-content-preinstalling-plugins) ?. Regarding the jenkins unlock, could you provide more information. I am not very sure what you mean.

I can't add sonar plugins in jenkins.
I try to groovy install sonar ,but configure sonar is failed.

**Comment by javsalgar** [comment]
Could you please provide the exact steps to reproduce the issue?
