### ISSUE TITLE
Upgrade to OpenJDK 11

### ISSUE THREAD

**Issue by tonyhhyip** [bitnami/bitnami-docker-jenkins#78]
### Name and Version

bitnami/jenkins:2

### What is the problem this feature will solve?

As OpenJDK 8 has reached EOL, upgrading to JDK 11 would help in provided bug fixes and security update.

### What is the feature you are proposing to solve the problem?

Upgrade the JDK in the image to use JDK 11. I could make the PR if this good looks to be done.

### What alternatives have you considered?

Split a image tag for jdk11. Due to the request from VMWare, using any image other than provided from Bitnami would be forbidden.

**Comment by tonyhhyip** [comment]
Just find PR already created on #71

**Comment by juan131** [comment]
Thanks for the request @tonyhhyip ! Please let's follow the conversation at https://github.com/bitnami/bitnami-docker-jenkins/pull/71

**Comment by carrodher** [comment]
Please note we just released a new container image using java 11, see https://github.com/bitnami/bitnami-docker-jenkins/commit/3da37f29dc0e50990362e7971b9a769021601e62.

This java version is going to be used starting from tag `2.319.3-debian-10-r13`.
