### ISSUE TITLE
how to get init log? I think is init failed,but can't find log path.

### ISSUE THREAD

**Issue by smarttang** [bitnami/bitnami-docker-jenkins#80]
### Name and Version

all

### What steps will reproduce the bug?

1. deployment to K8s.
2. i want get jenkins init log, lock for init-jenkins.groovy.tpl execute log.
3. i want change init-jenkins.groovy.tpl something job, simple: add sonar account, add gitlab account.

### What is the expected behavior?

RT 

### What do you see instead?

RT

### Additional information

RT

**Comment by smarttang** [comment]
我想表达的是，我想知道在哪可以看到初始化的LOG日志。
因为我在init-jenkins.groovy.tpl上加了点东西，现在想知道哪里可以看到报错，因为初始化的时候我把密码填进去了并创建了用户，现在失效了。

**Comment by smarttang** [comment]
```
jenkins 03:41:42.82 
jenkins 03:41:42.82 Welcome to the Bitnami jenkins container
jenkins 03:41:42.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
jenkins 03:41:42.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
jenkins 03:41:42.82 
jenkins 03:41:42.83 INFO  ==> Configuring libnss_wrapper
jenkins 03:41:42.84 INFO  ==> ** Starting Jenkins setup **
realpath: /usr/share/jenkins/ref: No such file or directory
jenkins 03:41:43.86 INFO  ==> Creating init script
jenkins 03:41:43.88 INFO  ==> Starting Jenkins in background
```
wait a long time.....

**Comment by javsalgar** [comment]
Hi,

Did you try deploying the chart with `image.debug=true`.

**Comment by smarttang** [comment]
Ok，i try again


发自我的iPhone

**Comment by smarttang** [comment]
I can't find the bug logs....

**Comment by smarttang** [comment]
jenkins 07:40:22.16 
jenkins 07:40:22.16 Welcome to the Bitnami jenkins container
jenkins 07:40:22.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
jenkins 07:40:22.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
jenkins 07:40:22.17 
jenkins 07:40:22.18 INFO  ==> Configuring libnss_wrapper
jenkins 07:40:22.19 INFO  ==> ** Starting Jenkins setup **
realpath: /usr/share/jenkins/ref: No such file or directory
jenkins 07:40:23.51 INFO  ==> Creating init script
jenkins 07:40:23.58 INFO  ==> Starting Jenkins in background


not anything....

**Comment by smarttang** [comment]
is download something?
