### ISSUE TITLE
jenkins - 2.332.2 - problem Failed to initialize the default JAR Cache location

### ISSUE THREAD

**Issue by BertuNet** [bitnami/bitnami-docker-jenkins#81]
### Name and Version

bitnami/jenkins:2.332.2

### What steps will reproduce the bug?

1. Installed on OpenShift
2. Default configuration

### What is the expected behavior?

No problem to write a jar into jenkins home jar cache directory

### What do you see instead?
```
WARNING: Could not create jar cache. Running without cache.
java.io.IOException: Failed to initialize the default JAR Cache location
	at hudson.remoting.JarCache.getDefault(JarCache.java:40)
	at hudson.remoting.ChannelBuilder.withJarCacheOrDefault(ChannelBuilder.java:238)
	at hudson.remoting.Launcher.main(Launcher.java:754)
	at hudson.remoting.Launcher.main(Launcher.java:742)
	at hudson.remoting.Launcher.main(Launcher.java:733)
	at hudson.remoting.Launcher.main(Launcher.java:729)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jenkins.maven3.agent.Maven33Main.main(Maven33Main.java:137)
	at jenkins.maven3.agent.Maven33Main.main(Maven33Main.java:65)
Caused by: java.lang.IllegalArgumentException: Root directory not writable: /.jenkins/cache/jars
	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:63)
	at hudson.remoting.JarCache.getDefault(JarCache.java:38)
	... 11 more
Caused by: java.nio.file.AccessDeniedException: /.jenkins
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:61)
```
### Additional information

Hi all,
I'm just updated Jenkins version from 2.303.1 to 2.332.2.
I've made a clean installation\setup (the same I used with the older version), but I have a problem when I try a job that needs to write in user.home directory, it seems that it does not take the correct directory.
I've not changed default settings about jenkins_home, etc.
If I come back to the older version, I've not have a problem :(

what may I have to check?

thank u,

regards

p.s. I've also tried the 2.332.1 and 2.319.3 versions.

**Comment by marcosbc** [comment]
Hi @BertuNet, note that we do not test on OpenShift, so we will not be able to reproduce your scenario.

That said, it seems like you are running some additional configuration apart from the default docker-compose: https://github.com/bitnami/bitnami-docker-jenkins/blob/master/docker-compose.yml

Could you share any customization you used to deploy Jenkins? Also note that by default `JENKINS_HOME` is set to `/bitnami/jenkins/home`, I don't understand where `/.jenkins` comes from.

**Comment by BertuNet** [comment]
> Hi @BertuNet, note that we do not test on OpenShift, so we will not be able to reproduce your scenario.
> 
> That said, it seems like you are running some additional configuration apart from the default docker-compose: https://github.com/bitnami/bitnami-docker-jenkins/blob/master/docker-compose.yml
> 
> Could you share any customization you used to deploy Jenkins? Also note that by default `JENKINS_HOME` is set to `/bitnami/jenkins/home`, I don't understand where `/.jenkins` comes from.

Hi @marcosbc ,
here step by step:

1. Download github files to generate custom docker image (i've just added a parameter to handle prefix in jenkins with -Djenkins)
2. Generate Image and push it on repo
3. Generate config with helm (values here)

`# Jenkins Image parameters
image:
  registry: registry.xxxxxx.com
  repository: jenkins-custom-image
  pullSecrets: ["nexus-registry-credentials"]
  tag: "2.332.2"
  pullPolicy: Always
  debug: true
# Jenkins Configuration parameters
jenkinsUser: xxxxxxxx
jenkinsPassword: xxxxxxxx
javaOpts:
  - "-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400 -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Xms1024m -Xmx8192m -XX:MaxPermSize=1024m  -Xss512k -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Rome -Djava.awt.headless=true"
extraEnvVars:
  - name: JENKINS_OPTS <-- new variable to handle prefix
    value: " --prefix=/jenkins "
#extraEnvVars  Array with extra environment variables to add to the Jenkins container  []
#extraEnvVarsCM  Name of existing ConfigMap containing extra env vars  "" 
#extraEnvVarsSecret  Name of existing Secret containing extra env vars "" 
# Jenkins deployment parameters
resources:
  limits:
    memory: 8G
  requests:
    cpu: '0.5'
    memory: 8G
podSecurityContext:
  enabled: true
  fsGroup: 1000550000
containerSecurityContext:
  enabled: true
  runAsUser: 1000550000
  runAsNonRoot: true
livenessProbe:
  enabled: false
customLivenessProbe:
  httpGet:
    path: /jenkins/login
    port: http
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: false
customReadinessProbe:
  httpGet:
    path: /jenkins/login
    port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1
# Traffic Exposure Parameters
service:
  type: ClusterIP
ingress:
  enabled: false
persistence:
  enabled: false
extraVolumes:
  - name: data-jenkins-dev
    persistentVolumeClaim:
      claimName: data-jenkins-dev
extraVolumeMounts:
  - name: data-jenkins-dev
    mountPath: /bitnami/jenkins/home`

i dunno where jenkins get "/.jenkins" path :( it's just weird that with a jenkins older version i've not a problem.
what may I have to check?

thank u,

regards

**Comment by marcosbc** [comment]
Hi @BertuNet, it could be that `/.jenkins` is parsed from the value of `-Duser.home`. Note that the current container image has the following line in `run.sh`:

```
args+=("-Duser.home=${JENKINS_HOME}" "-jar" "${JENKINS_BASE_DIR}/jenkins.war")
```

I would encourage you to try and enable debug in the `run.sh` script with `set -o xtrace`, and see what is the value of `-Duser.home`, as well as the value for other parameters.

**Comment by BertuNet** [comment]
Hi @marcosbc ,
i've added log, this is the result.
![image](https://user-images.githubusercontent.com/92080627/173604107-e215a7d9-9195-451d-997e-e418b630a106.png)


Now, if i try to start a build to compile a library with maven i get this error 
![image](https://user-images.githubusercontent.com/92080627/173603541-03e86ede-ec12-4dfe-b8e9-2176ead03562.png)


it's strange because if i look how build starts, i'm getting a correct jenkins home
![image](https://user-images.githubusercontent.com/92080627/173603761-9410ae28-ee8d-4735-805d-8b6537f36a4b.png)

Maybe some plugins needs other config (ex. maven) ?

what may I have to check?

Thanks,

Regards

**Comment by marcosbc** [comment]
@BertuNet I believe the issue is not `JENKINS_HOME` but the `user.home` Java property, which does not seem to be set properly. You could try and set a custom value via `-Duser.home=...` (the current default is `/bitnami/jenkins/home`).

Alternatively, you could try and extend the default Dockerfile to add a command to create `/.jenkins`, but that would likely mean Jenkins' home directory ends up pointing to that folder.
